const fs = require('fs');

// 151개 위험 키에 대한 한국어/영어 번역
const koTranslations = {
    accountHolder: "예금주",
    addWord: "추가",
    adminSystem: "관리 시스템",
    aiPracticeAnalysis: "AI 수련 분석",
    appInstallGuide: "앱 설치 안내",
    bannerInstallDesc: "홈 화면에 추가하면 더 빠르게 이용할 수 있습니다.",
    bannerInstallTitle: "앱 설치하기",
    bookingTab: "예약",
    calendarView: "캘린더 보기",
    cancel: "취소",
    cancelAttendance: "출석 취소",
    cashLabel: "현금",
    checkRecordBtn: "기록 확인",
    checkin_closed_sub: "운영 시간이 아닙니다.",
    checkin_closed_title: "출석 마감",
    checkin_confirm_question: "본인이 맞으신가요?",
    checkin_pin_alternative: "번호로 출석하기",
    checkin_touch_to_start: "터치하여 시작",
    classLabel: "수업",
    countUnit: "건",
    currentMembership: "현재 이용권",
    currentlyUsing: "이용중",
    daysLeft: "일 남음",
    deferRules: "홀딩 규정",
    demoAutoLogin: "데모 자동 로그인",
    emailLabel: "이메일",
    endDate: "종료일",
    expiryDate: "만료일",
    facereg_status: "얼굴 등록 상태",
    facereg_title: "얼굴 등록",
    guideAndroid: "Android",
    guideAndroidStep1Desc: "Chrome 브라우저의 메뉴(⋮)를 탭합니다.",
    guideAndroidStep1Title: "메뉴 열기",
    guideAndroidStep2Desc: "'홈 화면에 추가'를 탭합니다.",
    guideAndroidStep2Title: "홈 화면에 추가",
    guideAndroidStep3Desc: "'추가' 또는 '설치'를 탭합니다.",
    guideChromeHint: "Chrome 브라우저에서 열어주세요.",
    guideIOS: "iOS (iPhone/iPad)",
    guideIOSStep1Desc: "Safari 하단의 공유(⬆) 버튼을 탭합니다.",
    guideIOSStep1Title: "공유 버튼 탭",
    guideIOSStep2Desc: "'홈 화면에 추가'를 탭합니다.",
    guideIOSStep2Title: "홈 화면에 추가",
    guideIOSStep3Desc: "우측 상단 '추가'를 탭합니다.",
    guideInstallDone: "설치 완료!",
    guideSafariHint: "Safari 브라우저에서 열어주세요.",
    holdBtnLabel: "홀딩 신청",
    holdModalTitle: "이용권 홀딩",
    holdNoteAuto: "홀딩 기간이 끝나면 자동으로 해제됩니다.",
    holdNoteExtend: "홀딩한 만큼 종료일이 연장됩니다.",
    holdPauseTitle: "이용 일시정지",
    holdSelectPeriod: "홀딩 기간 선택",
    holdingStatus: "홀딩 중",
    inAppBrowserWarning: "외부 브라우저에서 열어주세요.",
    installApp: "앱 설치",
    installBtn: "설치하기",
    installGuideConfirm: "확인",
    installGuideSub: "2단계로 간편 설치",
    installGuideTitle: "앱 설치 가이드",
    installWord: "설치",
    iosShareStep1: "Safari 하단 공유 버튼 탭",
    iosShareStep2: "홈 화면에 추가 탭",
    kakaoSupport: "카카오톡 상담",
    legend_intensive: "집중 수업",
    legend_my_practice: "내 수련",
    legend_pregnancy: "산전 수업",
    legend_regular: "정규 수업",
    legend_saturday: "토요 수업",
    listView: "목록 보기",
    loadMoreAttendance: "출석 더 보기",
    loadMoreN: "더 보기",
    loading: "로딩 중...",
    loadingPayment: "결제 정보 로딩 중...",
    loginFooter: "로그인 문의: 원장님께 연락하세요.",
    loginSub: "로그인하여 시작하세요.",
    loginTitle: "로그인",
    loginWelcome: "환영합니다",
    logout: "로그아웃",
    longTermDiscount: "장기 할인",
    management: "관리",
    meditation: "명상",
    messagesSubtitle: "원장님이 보낸 메시지",
    messagesTitle: "메시지",
    monthUnit: "개월",
    myPassStatus: "내 이용권 현황",
    myYogaTaste: "나의 요가 취향",
    nameLabel: "이름",
    namePlaceholder: "이름을 입력하세요",
    navAIAssistant: "AI 어시스턴트",
    navAlertHistory: "알림 이력",
    navAttendance: "출석",
    navBookings: "예약",
    navData: "데이터",
    navGuide: "가이드",
    navKiosk: "키오스크",
    navMembers: "회원",
    navNotices: "공지",
    navPricing: "요금",
    navRevenue: "매출",
    navSchedule: "시간표",
    navSettings: "설정",
    navTrash: "휴지통",
    nim: "님",
    no: "아니요",
    noAttendanceHistory: "출석 기록이 없습니다.",
    noMessages: "메시지가 없습니다.",
    noNewNotices: "새 공지가 없습니다.",
    noPaymentHistory: "결제 내역이 없습니다.",
    noTimetableImage: "시간표 이미지가 없습니다.",
    notEnoughData: "데이터가 부족합니다.",
    noticesTitle: "공지사항",
    paidOn: "결제일",
    passwordLabel: "비밀번호",
    paymentAccount: "입금 계좌",
    paymentHistory: "결제 내역",
    phoneLabel: "전화번호",
    phonePlaceholder: "010-0000-0000",
    practiceHistory: "수련 이력",
    preRegistered: "사전등록",
    preview: "미리보기",
    privacy_policy: "개인정보처리방침",
    pushNotification: "푸시 알림",
    pushNotificationDesc: "수업 알림 및 공지사항을 받을 수 있습니다.",
    pushNotificationTitle: "알림 설정",
    recentAttendance: "최근 출석",
    remainCount: "잔여 횟수",
    remainingCredits: "잔여 횟수",
    scheduleSub: "수업 시간표를 확인하세요.",
    scheduleTitle: "시간표",
    settingUp: "설정 중...",
    sixMonthDiscount: "6개월 할인",
    startDate: "시작일",
    stats_empty: "통계 데이터가 없습니다.",
    stats_title: "통계",
    tabHistory: "이력",
    tabHome: "홈",
    tabMessages: "메시지",
    tabNotices: "공지",
    tabPrices: "요금",
    tabSchedule: "시간표",
    threeMonthDiscount: "3개월 할인",
    ticketType: "이용권 종류",
    times: "회",
    timetableLabel: "시간표",
    todayWisdom: "오늘의 지혜",
    tuitionFee: "수강료",
    viewAll: "전체보기",
    viewCalendar: "캘린더로 보기",
    viewNotice: "공지 보기",
    viewWeekly: "주간 보기",
    won: "원",
    yes_thats_me: "네, 맞아요"
};

const enTranslations = {
    accountHolder: "Account Holder",
    addWord: "Add",
    adminSystem: "Admin System",
    aiPracticeAnalysis: "AI Practice Analysis",
    appInstallGuide: "App Installation Guide",
    bannerInstallDesc: "Add to home screen for faster access.",
    bannerInstallTitle: "Install App",
    bookingTab: "Bookings",
    calendarView: "Calendar View",
    cancel: "Cancel",
    cancelAttendance: "Cancel Attendance",
    cashLabel: "Cash",
    checkRecordBtn: "Check Record",
    checkin_closed_sub: "Outside operating hours.",
    checkin_closed_title: "Check-in Closed",
    checkin_confirm_question: "Is this you?",
    checkin_pin_alternative: "Check in with PIN",
    checkin_touch_to_start: "Touch to start",
    classLabel: "Class",
    countUnit: "records",
    currentMembership: "Current Membership",
    currentlyUsing: "In Use",
    daysLeft: "days left",
    deferRules: "Hold Policy",
    demoAutoLogin: "Demo Auto Login",
    emailLabel: "Email",
    endDate: "End Date",
    expiryDate: "Expiry Date",
    facereg_status: "Face Registration Status",
    facereg_title: "Face Registration",
    guideAndroid: "Android",
    guideAndroidStep1Desc: "Tap the menu (⋮) in Chrome browser.",
    guideAndroidStep1Title: "Open Menu",
    guideAndroidStep2Desc: "Tap 'Add to Home Screen'.",
    guideAndroidStep2Title: "Add to Home Screen",
    guideAndroidStep3Desc: "Tap 'Add' or 'Install'.",
    guideChromeHint: "Please open in Chrome browser.",
    guideIOS: "iOS (iPhone/iPad)",
    guideIOSStep1Desc: "Tap the Share (⬆) button at the bottom of Safari.",
    guideIOSStep1Title: "Tap Share Button",
    guideIOSStep2Desc: "Tap 'Add to Home Screen'.",
    guideIOSStep2Title: "Add to Home Screen",
    guideIOSStep3Desc: "Tap 'Add' in the top right.",
    guideInstallDone: "Installation Complete!",
    guideSafariHint: "Please open in Safari browser.",
    holdBtnLabel: "Apply Hold",
    holdModalTitle: "Membership Hold",
    holdNoteAuto: "Hold will be automatically released when the period ends.",
    holdNoteExtend: "End date will be extended by the hold period.",
    holdPauseTitle: "Pause Membership",
    holdSelectPeriod: "Select Hold Period",
    holdingStatus: "On Hold",
    inAppBrowserWarning: "Please open in an external browser.",
    installApp: "Install App",
    installBtn: "Install",
    installGuideConfirm: "Confirm",
    installGuideSub: "Easy 2-step installation",
    installGuideTitle: "App Installation Guide",
    installWord: "Install",
    iosShareStep1: "Tap Safari share button",
    iosShareStep2: "Tap Add to Home Screen",
    kakaoSupport: "KakaoTalk Support",
    legend_intensive: "Intensive",
    legend_my_practice: "My Practice",
    legend_pregnancy: "Prenatal",
    legend_regular: "Regular",
    legend_saturday: "Saturday",
    listView: "List View",
    loadMoreAttendance: "Load More Attendance",
    loadMoreN: "Load More",
    loading: "Loading...",
    loadingPayment: "Loading payment info...",
    loginFooter: "For login issues, contact your studio.",
    loginSub: "Sign in to get started.",
    loginTitle: "Login",
    loginWelcome: "Welcome",
    logout: "Logout",
    longTermDiscount: "Long-term Discount",
    management: "Management",
    meditation: "Meditation",
    messagesSubtitle: "Messages from your studio",
    messagesTitle: "Messages",
    monthUnit: "months",
    myPassStatus: "My Pass Status",
    myYogaTaste: "My Yoga Preferences",
    nameLabel: "Name",
    namePlaceholder: "Enter your name",
    navAIAssistant: "AI Assistant",
    navAlertHistory: "Alert History",
    navAttendance: "Attendance",
    navBookings: "Bookings",
    navData: "Data",
    navGuide: "Guide",
    navKiosk: "Kiosk",
    navMembers: "Members",
    navNotices: "Notices",
    navPricing: "Pricing",
    navRevenue: "Revenue",
    navSchedule: "Schedule",
    navSettings: "Settings",
    navTrash: "Trash",
    nim: "",
    no: "No",
    noAttendanceHistory: "No attendance history.",
    noMessages: "No messages.",
    noNewNotices: "No new notices.",
    noPaymentHistory: "No payment history.",
    noTimetableImage: "No timetable image available.",
    notEnoughData: "Not enough data.",
    noticesTitle: "Notices",
    paidOn: "Paid on",
    passwordLabel: "Password",
    paymentAccount: "Payment Account",
    paymentHistory: "Payment History",
    phoneLabel: "Phone",
    phonePlaceholder: "010-0000-0000",
    practiceHistory: "Practice History",
    preRegistered: "Pre-registered",
    preview: "Preview",
    privacy_policy: "Privacy Policy",
    pushNotification: "Push Notifications",
    pushNotificationDesc: "Receive class reminders and announcements.",
    pushNotificationTitle: "Notification Settings",
    recentAttendance: "Recent Attendance",
    remainCount: "Remaining",
    remainingCredits: "Remaining Credits",
    scheduleSub: "Check the class schedule.",
    scheduleTitle: "Schedule",
    settingUp: "Setting up...",
    sixMonthDiscount: "6-Month Discount",
    startDate: "Start Date",
    stats_empty: "No statistics data.",
    stats_title: "Statistics",
    tabHistory: "History",
    tabHome: "Home",
    tabMessages: "Messages",
    tabNotices: "Notices",
    tabPrices: "Pricing",
    tabSchedule: "Schedule",
    threeMonthDiscount: "3-Month Discount",
    ticketType: "Pass Type",
    times: "times",
    timetableLabel: "Timetable",
    todayWisdom: "Today's Wisdom",
    tuitionFee: "Tuition Fee",
    viewAll: "View All",
    viewCalendar: "Calendar View",
    viewNotice: "View Notice",
    viewWeekly: "Weekly View",
    won: "₩",
    yes_thats_me: "Yes, that's me"
};

// translations.js 파일에 키 주입
let content = fs.readFileSync('src/utils/translations.js', 'utf8');

// ko 블록에 추가 (ko: { 바로 뒤에)
const koInsert = Object.entries(koTranslations)
    .map(([k, v]) => `        "${k}": "${v}"`)
    .join(',\n');

// en 블록에 추가 (en: { 바로 뒤에)  
const enInsert = Object.entries(enTranslations)
    .map(([k, v]) => `        "${k}": "${v}"`)
    .join(',\n');

// 이미 있는 키는 스킵하고 없는 키만 추가
let koAdded = 0, enAdded = 0;
Object.entries(koTranslations).forEach(([k, v]) => {
    const re = new RegExp('"' + k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '"\\s*:');
    // ko 블록에서 찾기
    const koStart = content.indexOf('ko:');
    const enStart = content.indexOf('en:');
    const koSection = content.substring(koStart, enStart);
    if (!re.test(koSection)) {
        // ko: { 바로 뒤에 추가
        content = content.replace(/(ko\s*:\s*\{)/, `$1\n        "${k}": "${v}",`);
        koAdded++;
    }
});

Object.entries(enTranslations).forEach(([k, v]) => {
    const re = new RegExp('"' + k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '"\\s*:');
    const enStart = content.indexOf('en:');
    const enSection = content.substring(enStart);
    if (!re.test(enSection)) {
        content = content.replace(/(en\s*:\s*\{)/, `$1\n        "${k}": "${v.replace(/"/g, '\\"')}",`);
        enAdded++;
    }
});

fs.writeFileSync('src/utils/translations.js', content);
console.log(`✅ ko 블록에 ${koAdded}개 키 추가`);
console.log(`✅ en 블록에 ${enAdded}개 키 추가`);
